language: ruby
cache: bundler
rvm:
  - "1.9.3"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: DISPLAY=:99.0 bundle exec cucumber --profile unshred_on_travis_ci
